export const SCROLL_SIZE_KEYS = {
  DASHBOARD: {
    ROOT: 'DASHBOARD_ROOT',
    TAB_CONTENT_ROOT: 'DASHBOARD_TAB_CONTENT_ROOT',
    APP: {
      APP_FEATURED_GRID_ITEM: 'DASHBOARD_APP_APP_FEATURED_GRID_ITEM',
    },
  },
}
